# Site settings
title: Mohammed Husain
description: Personal Website/Portfolio/Resume
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mohammed Husain
user_description: I'm a recent Georgia Tech graduate looking to dive into UX Research and Design. My focus is in Human-Computer Interaction and Media creation, and I'm always looking for a challenge! Check out some of my past work below.
user_title: UI/UX Designer
email: mobhusain@gmail.com
# twitter_username: lorem_ipsum
github_username: Paperslate
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
livereload: true
